// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
// import { config } from "dotenv";
import { defineConfig, env } from "prisma/config";

// Load .env.local first, then .env (local takes precedence)
// config({ path: ".env.local" });
// config({ path: ".env" });

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx lib/prisma.ts",
  },
  datasource: {
    url: env("DATABASE_URL"),
  },
});
